In [1]:
import numpy as np

In [3]:
arr = np.random.rand(5,5)

In [4]:
arr

array([[0.92192467, 0.49716166, 0.07818089, 0.88463776, 0.03960145],
       [0.24894568, 0.09482388, 0.74799472, 0.07832192, 0.64590997],
       [0.32868938, 0.25810547, 0.7924292 , 0.99667838, 0.39343031],
       [0.06954712, 0.04242531, 0.94683672, 0.23924463, 0.63482575],
       [0.16630097, 0.12228198, 0.96174206, 0.59430084, 0.85658226]])

In [5]:
arr.shape

(5, 5)

In [6]:
arr.dtype

dtype('float64')

In [7]:
arr[:4]

array([[0.92192467, 0.49716166, 0.07818089, 0.88463776, 0.03960145],
       [0.24894568, 0.09482388, 0.74799472, 0.07832192, 0.64590997],
       [0.32868938, 0.25810547, 0.7924292 , 0.99667838, 0.39343031],
       [0.06954712, 0.04242531, 0.94683672, 0.23924463, 0.63482575]])

In [8]:
arr[:4].shape

(4, 5)

In [9]:
arr[1,1]

0.09482388060344171

In [10]:
arr[:-1]

array([[0.92192467, 0.49716166, 0.07818089, 0.88463776, 0.03960145],
       [0.24894568, 0.09482388, 0.74799472, 0.07832192, 0.64590997],
       [0.32868938, 0.25810547, 0.7924292 , 0.99667838, 0.39343031],
       [0.06954712, 0.04242531, 0.94683672, 0.23924463, 0.63482575]])

In [11]:
int_arr = np.random.randint(5, size = (6,8))

In [12]:
int_arr

array([[4, 4, 4, 0, 1, 3, 0, 0],
       [2, 1, 0, 1, 4, 4, 0, 0],
       [1, 0, 4, 3, 2, 4, 0, 3],
       [0, 3, 0, 1, 3, 2, 3, 2],
       [1, 4, 1, 3, 3, 2, 2, 4],
       [1, 1, 0, 1, 3, 0, 4, 1]])

In [13]:
int_arr_0 = int_arr[0]

In [14]:
int_arr_0

array([4, 4, 4, 0, 1, 3, 0, 0])

In [15]:
int_arr_0 == 0

array([False, False, False,  True, False, False,  True,  True])

In [16]:
int_arr_0_is_012 = (int_arr_0 == 0) | (int_arr_0 == 1) | (int_arr_0 == 2)

In [17]:
int_arr_0_is_012

array([False, False, False,  True,  True, False,  True,  True])

In [18]:
int_arr_0[int_arr_0_is_012]

array([0, 1, 0, 0])