In [35]:
import numpy as np

In [36]:
marks = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]

In [37]:
marks_transpose = []
for j in range(len(marks[0])):
    marks_transpose.append([])
    for i in range(len(marks)):
        marks_transpose[j].append(marks[i][j])

In [38]:
marks_transpose

[[1, 5, 9], [2, 6, 10], [3, 7, 11], [4, 8, 12]]

In [39]:
marks_array = np.array(marks)

In [40]:
marks_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [41]:
marks_array.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [42]:
marks_array.sum(axis = 1)/60

array([0.16666667, 0.43333333, 0.7       ])

In [43]:
marks_array.T.sum(axis = 1)/60

array([0.25, 0.3 , 0.35, 0.4 ])

In [44]:
marks_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [45]:
grace_marks = np.array([[1,2,3]]).T

In [46]:
marks_array + grace_marks

array([[ 2,  3,  4,  5],
       [ 7,  8,  9, 10],
       [12, 13, 14, 15]])

In [47]:
grace_marks.shape

(3, 1)

In [48]:
marks

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [55]:
weight_list = [[0.4, 0.2, 0.2, 0.2]]

In [56]:
weight_list

[[0.4, 0.2, 0.2, 0.2]]

In [57]:
results = []
for i in range(len(marks)):
    for j in range(len(weight_list)):
        curr_sum = 0
        for k in range(len(marks[i])):
            curr_sum += marks[i][k]*weight_list[j][k]
        results.append(curr_sum)

In [58]:
results

[2.2, 6.200000000000001, 10.2]

In [59]:
marks_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [60]:
weigh_array = np.array(weigh_list)

In [62]:
weigh_array.T

array([[0.4, 0.2, 0.2, 0.2]])

In [63]:
marks_array @ weigh_array

array([[ 2.2],
       [ 6.2],
       [10.2]])

In [64]:
marks_array.shape

(3, 4)

In [65]:
weigh_array.shape

(4, 1)