In [3]:
import numpy as np

In [4]:
python_list = [1,3,5,-5,6]

In [5]:
python_list

[1, 3, 5, -5, 6]

In [6]:
numpy_arr = np.array(python_list)

In [7]:
numpy_arr.shape

(5,)

In [8]:
len(numpy_arr.shape)

1

In [9]:
python_list_list = [[1,2],[3,4]]

In [10]:
numpy_arr2 = np.array(python_list_list)

In [11]:
numpy_arr2.shape

(2, 2)

In [12]:
len(numpy_arr2.shape)

2

In [13]:
python_list_list = [[1,2,3],[3,4,5]]

In [14]:
np.array(python_list_list).shape

(2, 3)

In [15]:
list(range(5))

[0, 1, 2, 3, 4]

In [16]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [17]:
np.zeros((2,2,2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [18]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [ ]:
import numpy
a = input().split()
my_array = numpy.array(a)
print(numpy.shape(my_array,(3,3)))